# Generated by Django 4.0.6 on 2022-07-05 23:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel_veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='data_devolucao',
            field=models.DateField(default=datetime.datetime(2022, 7, 5, 23, 23, 24, 282779, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='data_retirada',
            field=models.DateField(default=datetime.datetime(2022, 7, 5, 23, 23, 24, 282779, tzinfo=utc)),
        ),
    ]
