# Generated by Django 4.0.5 on 2022-06-30 21:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('folha_pagamento', '0002_cargos_funcionario_cpf_funcionario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 21, 29, 9, 84980, tzinfo=utc)),
        ),
    ]
