# Generated by Django 4.0.5 on 2022-06-30 22:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('folha_pagamento', '0003_funcionario_data_admissao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cargos',
            new_name='Cargo',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 22, 11, 8, 174946, tzinfo=utc)),
        ),
    ]
