# Generated by Django 4.0.5 on 2022-07-02 23:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('endereco', models.CharField(default='', max_length=100)),
                ('telefone', models.CharField(default='', max_length=14)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('tipo', models.CharField(choices=[('PF', 'Física'), ('PJ', 'Jurídica')], default='PF', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(default='', max_length=7)),
                ('km', models.FloatField(default=0)),
                ('carga', models.FloatField(default=0)),
                ('bagageiro', models.IntegerField(default=0)),
                ('portas', models.CharField(choices=[('VL', 'Automóvel'), ('VP', 'Caminhão')], default='VL', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField(default=datetime.datetime(2022, 7, 2, 23, 31, 37, 179010, tzinfo=utc))),
                ('data_devolucao', models.DateField(default=datetime.datetime(2022, 7, 2, 23, 31, 37, 179010, tzinfo=utc))),
                ('km_rodado', models.FloatField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel_veiculo.cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel_veiculo.veiculo')),
            ],
            options={
                'verbose_name_plural': 'Aluguéis',
            },
        ),
    ]
