# Generated by Django 4.0.5 on 2022-06-30 23:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel_veiculo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluguel',
            old_name='Cliente',
            new_name='cliente',
        ),
        migrations.AddField(
            model_name='aluguel',
            name='data_devolucao',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 23, 23, 37, 839316, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='data_retirada',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 23, 23, 37, 839316, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='km_rodado',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('PJ', 'Física'), ('PJ', 'Jurídica')], default='PJ', max_length=2),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='bagageiro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='carga',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='km',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='portas',
            field=models.CharField(choices=[('VL', 'Automóvel'), ('VP', 'Caminhão')], default='VL', max_length=2),
        ),
    ]
