# Generated by Django 4.0.5 on 2022-06-30 23:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel_veiculo', '0003_alter_aluguel_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluguel',
            options={'verbose_name_plural': 'Aluguéis'},
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='data_devolucao',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 23, 45, 51, 944205, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='data_retirada',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 23, 45, 51, 944205, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
