# Generated by Django 4.0.5 on 2022-07-01 00:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel_veiculo', '0004_alter_aluguel_options_alter_aluguel_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='data_devolucao',
            field=models.DateField(default=datetime.datetime(2022, 7, 1, 0, 5, 5, 891149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='data_retirada',
            field=models.DateField(default=datetime.datetime(2022, 7, 1, 0, 5, 5, 891149, tzinfo=utc)),
        ),
    ]
